# Project information
site_name: Virny
site_description: Responsible AI Toolset in Python

# Repository
repo_name: DataResponsibly/virny
repo_url: https://github.com/DataResponsibly/Virny
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2024

# Theme configuration
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  palette:
    primary: deep purple
    accent: deep purple
  font:
    text: Open Sans
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes

# Extras
extra:
  analytics:
    provider: google
    property: UA-63302552-3
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/DataResponsibly/Virny
  version:
    provider: mike

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
      toc_depth: "1-3"
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages
  - mike
  - redirects:
      redirect_maps:
        index.md: introduction/welcome_to_virny.md

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
