# Project information
site_name: Virny
site_description: Responsible AI Toolset in Python

# Repository
repo_name: virny
repo_url: https://github.com/FalaahArifKhan/fairness-variance/tree/denys
edit_uri: ""

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Rubik
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.indexes

# Extras
extra:
  analytics:
    provider: google
    property: UA-63302552-3
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/FalaahArifKhan/fairness-variance/tree/denys
  version:
    provider: mike

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
      toc_depth: "1-3"
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages
  - mike

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
