name: unit-tests

on:
  workflow_call:
    inputs:
      python:
        type: string
      os:
        type: string

jobs:
  test:
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Retrieve the environment and the Virny build
        uses: ./.github/actions/retrieve-env
        with:
          python: ${{ inputs.python }}

      - name: pytest [Branch]
        run: |
          source ~/.venv/bin/activate
          pip install requests-toolbelt==1.0.0
          pytest --durations=10 -n logical # Run pytest on all logical CPU cores
